version: "3"

services:
  langgraph-api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/api
      - DATABASE_URI=postgresql://postgres:postgres@langgraph-postgres:5432/postgres
      - REDIS_URI=redis://langgraph-redis:6379
      - ASYNC_BACKEND=POSTGRES
    depends_on:
      - langgraph-postgres
      - langgraph-redis
    # command: /storage/entrypoint.sh

  langgraph-postgres:
    image: "pgvector/pgvector:pg16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - langgraph-data:/var/lib/postgresql/data

  langgraph-redis:
    image: "redis:6"
    ports:
      - "6379:6379"

volumes:
  langgraph-data: