# 개발 전용 override (docker compose up 시 자동 병합)
# 프로덕션 배포에서는 이 파일을 제외하고 실행하여 불변 이미지를 사용.

services:
  langgraph-api:
    # 소스 코드 변경 즉시 반영 (이미지 재빌드 불필요)
    volumes:
      - ./:/deps/ET_Agent:rw
    environment:
      # 개발 플래그 (애플리케이션이 참고하도록 선택적으로 사용)
      RUN_IN_CONTAINER: "1"
      REDIS_DEBUG: "false"
    # 필요 시 기본 명령을 재정의해 핫 리로드 활성화 (이미 엔트리포인트가 uvicorn 비슷하다면 생략 가능)
    # command: ["uvicorn", "langgraph_api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # 위 command를 사용하려면 실제 모듈 경로를 확인 후 수정.

  # 다른 서비스(선택)에도 개발 편의 세팅 추가 가능
  # redis:
  #   ports:
  #     - "6380:6379"  # 이미 base compose에 있다면 생략
