[project]
name = "pdf-quiz-rag"
version = "0.1.0"
description = "PDF 기반 객관식 문제 자동 출제 시스템 (RAG + LangGraph)"
requires-python = ">=3.12"
dependencies = [
    "langchain-ollama>=0.1.0",
    "pypdf[crypto]>=4.0.0",
    "ddgs>=9.5.2",
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.72",
    "langgraph>=0.6.3",
    "openai>=1.98.0",
    "redis>=6.2.0",
    "streamlit>=1.48.0",
    "wikipedia>=1.4.0",
    "langchain-huggingface>=0.3.1",
    "langchain-milvus>=0.2.1",
    "langchain-openai>=0.3.28",
    "opencv-python>=4.12.0.88",
    "pillow>=11.3.0",
    "pymilvus>=2.5.14",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.1.1",
    "reportlab>=4.4.3",
    "sentence-transformers>=5.0.0",
    "faiss-cpu>=1.7.4",
    "tiktoken>=0.9.0",
    "transformers>=4.35.0",
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "requests>=2.28.0",
    "any>=0.0.2",
    "groq>=0.31.0",
    "langchain-groq>=0.3.7",
    "graphviz>=0.21",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["common", "farmer", "teacher"]
