[project]
name = "et-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "duckduckgo-search>=8.1.1",
    "langchain>=0.3.27",
    "langgraph>=0.6.3",
    "openai>=1.98.0",
    "redis>=6.2.0",
    "wikipedia>=1.4.0",
]
