[project]
name = "pdf-quiz-rag"
version = "0.1.0"
description = "PDF 기반 객관식 문제 자동 출제 시스템 (RAG + LangGraph)"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.1.0",
    "langchain-community>=0.0.20",
    "langchain-huggingface>=0.0.1",
    "langchain-ollama>=0.1.0",
    "langgraph>=0.0.30",
    "pypdf[crypto]>=4.0.0",
    "faiss-cpu>=1.7.4",
    "sentence-transformers>=2.2.0",
    "transformers>=4.35.0",
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "requests>=2.28.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"